version: '3.9'
services:
  db:
    image: mysql:8.0.31
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d
      - ./docker/db/init_data:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bbs
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: 1
  web:
    build:
      context: docker/web
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
    command: /bin/bash -c  "composer install && apachectl -D FOREGROUND"
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"